### ISSUE TITLE
HTML Issue.

### ISSUE THREAD

**Issue by KyleMcComb** [brumm/atom-highlight-colors#1]
When you type in a color e.g. "Green" like in a paragraph, it will show the color.

Please see the following screenshot below.
![color-highlight-issue](https://user-images.githubusercontent.com/40238351/55475168-121c8a00-560b-11e9-8128-2c3e562a4c6b.PNG)

Other than that, it's a really nice package and displays colours really accurately!

Thanks :D

**Comment by brumm** [comment]
Hey! Thanks for the praise and your issue! I think I missed a bunch of notifications about this, so apologies that I'm a bit late to reply.

I can definitely see how highlighting color-like words would be annoying :) I wanted to keep this stuff super simple, so there's no mechanism to even ignore certain syntaxes.

That said, I could imagine providing a toggle to optionally ignore color words for matching. Would that help?

**Comment by brumm** [comment]
Hey, found some time to do get this done, let me know whether it works for you :)
