### ISSUE TITLE
Highlighting Class Names

### ISSUE THREAD

**Issue by andrewvink** [brumm/atom-highlight-colors#4]
Hey Brumm,

Just noticed the package is highlighting class names in my SCSS.

![Highlighting Red](https://i.imgur.com/Pe8z3P0.png)

also class names in HTML

![Highlighting Classes HTML](https://i.imgur.com/3kfSd6I.png)

Checking a few things

***DOES** highlight the following*
```css

.text-red { }  

.blue { }

.something-something-blue { }

.something--blue { }

.something {
  .nested-blue {
    .nested-green {}
  }
}

```

*Does **NOT** highlight the following*
```css

.somethingblue { }

```

Thought you'd like to know for improvements - great package btw, loads super quick!

Quickly looking at it - the regex below might work in 'regexes.js'

```js
// Needs testing
`(?:[^\.|-])\b${color}\b`

```

Keep up the great work :)

**Comment by brumm** [comment]
Hey, thanks for the report. I'm not super interested in handling more edge cases around figuring out which parts should be highlighted and which should not be. That said, I could imagine an option for turning off highlghting for css color names, as suggested here: https://github.com/brumm/atom-highlight-colors/issues/1#issuecomment-506656600. What do you think?

**Comment by andrewvink** [comment]
Hey @brumm, no worries!

Yeah that would be awesome :)

Been using this package for over a week now and it's great, loads ALOT faster than the pigments package.

Appreciate the effort you put into so far!

**Comment by brumm** [comment]
Hey, found some time to do get this done, let me know whether it works for you :)

**Comment by andrewvink** [comment]
Awesome!! Thanks @brumm will check it out.
